# Use Go base image
FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Go binary
RUN go build -o main .

# Create a smaller production image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

# Expose the Gin app's port
EXPOSE 5000

# Run the binary
CMD ["./main"]
