# Dockerfile.dev
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code into the container
COPY . .

# Expose port 4200 for Angular dev server
EXPOSE 4200

# Start the Angular development server
CMD ["ng", "serve", "--configuration", "development", "--host", "0.0.0.0"]