# Step 1: Build the Angular app
FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

# Build the Angular app
RUN npm run build --prod

# Step 2: Serve the app with Nginx
FROM nginx:alpine

COPY --from=build /app/dist/market-league-front-end /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
