# Dockerfile.dev
FROM golang:1.23-alpine

# Install necessary tools
RUN apk add --no-cache git bash

# Install Air for live-reloading by specifying a known working commit hash
RUN go install github.com/cosmtrek/air@v1.40.4

# Set the working directory inside the container
WORKDIR /app

# Copy Go modules and install dependencies
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Expose the port Gin will run on
EXPOSE 9000

# Start the Air live-reload
CMD ["air"]